apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: config-server-deployment
  name: config-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: config-server
    spec:
      containers:
      - image: hanhnguyenduc999/config-server:latest
        name: config-server
        resources: {}
        ports:
          - containerPort: 8123
        envFrom:
          - configMapRef:
              name: redis-account
          - configMapRef:
              name: cm-config-server
          - configMapRef:
              name: db-account

status: {}
