apiVersion: apps/v1
kind: Deployment
metadata:
        name: dp-smartivr-config-server
        labels:
                app: smartivr-config-server
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: smartivr-config-server
        template:
                metadata:
                        labels:
                                app: smartivr-config-server
                spec:
                        containers:
                                - name: smartivr-config-server
                                  image: "smartivr-config-server:latest"
                                  imagePullPolicy: IfNotPresent
                                  volumeMounts:
                                          - name: config
                                            mountPath: /app/conf
                                            readOnly: true
                        volumes:
                                - name: config
                                  configMap:
                                          name: cm-smartivr-config-server
                                          items:
                                                  - key: "app.ini"
                                                    path: "app.ini"
                                                  - key: "conf.go"
                                                    path: "conf.go"
