apiVersion: v1
kind: Service
metadata:
        name: service-smartivr-config-server
        labels:
                app: smartivr-config-server
        namespace: smartivr
spec:
        selector:
                app: smartivr-config-server

        ports:
                - port: 8125
                  targetPort: 8125
