apiVersion: v1
kind: Service
metadata:
  name: service-config-server
spec:
  type: NodePort
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 30001